### ISSUE TITLE
Message fails to send with a JSON parser exception

### ISSUE THREAD

**Issue by milosmns** [Commit451/mailgun#1]
Adding more info...

**Comment by milosmns** [comment]
Hi,

I'm using the lib for the first time, I might be doing something wrong, but whenever I send an email, there is an exception that crashes the runtime.

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'newsSubscriberController': Invocation of init method failed; nested exception is java.lang.RuntimeException: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at com.appifyhub.service.ApplicationKt.main(Application.kt:14) [classes/:na]
Caused by: java.lang.RuntimeException: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:91) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.Single.blockingGet(Single.java:2154) ~[rxjava-2.1.3.jar:2.1.3]
	at com.appifyhub.service.utils.Utils.sendEmail(Utils.kt:106) ~[classes/:na]
	at com.appifyhub.service.utils.Utils.sendEmail$default(Utils.kt:100) ~[classes/:na]
	at com.appifyhub.service.service.NewsSubscriberService.createSubscriber(NewsSubscriberService.kt:40) ~[classes/:na]
	at com.appifyhub.service.service.NewsSubscriberService.createSubscriber$default(NewsSubscriberService.kt:29) ~[classes/:na]
	at com.appifyhub.service.controller.NewsSubscriberController.initFakeData(NewsSubscriberController.kt:36) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_92]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_92]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 18 common frames omitted
Caused by: com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
	at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:213) ~[moshi-1.5.0.jar:na]
	at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1012) ~[moshi-1.5.0.jar:na]
	at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:345) ~[moshi-1.5.0.jar:na]
	at com.squareup.moshi.JsonUtf8Reader.peek(JsonUtf8Reader.java:172) ~[moshi-1.5.0.jar:na]
	at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:125) ~[moshi-1.5.0.jar:na]
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:35) ~[moshi-1.5.0.jar:na]
	at com.commit451.mailgun.Mailgun$sendMessage$1.apply(Mailgun.kt:51) ~[mailgun-1.0.1.jar:na]
	at com.commit451.mailgun.Mailgun$sendMessage$1.apply(Mailgun.kt:11) ~[mailgun-1.0.1.jar:na]
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:76) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.internal.operators.observable.ObservableSingleSingle$SingleElementObserver.onComplete(ObservableSingleSingle.java:111) ~[rxjava-2.1.3.jar:2.1.3]
	at com.commit451.ehhttp.CallObservable.subscribeActual(CallObservable.kt:26) ~[ehhttp-1.0.0.jar:na]
	at io.reactivex.Observable.subscribe(Observable.java:10903) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.Single.subscribe(Single.java:2700) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.Single.subscribe(Single.java:2700) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.Single.blockingGet(Single.java:2153) ~[rxjava-2.1.3.jar:2.1.3]
	... 30 common frames omitted
```

So as you might have guessed, I'm using the lib inside a Spring Boot project (fairly simple at this point), all written in Kotlin.

**Comment by milosmns** [comment]
And here is what I'm doing:

1. Preparing some fake data to have it in the DB

```kotlin
    // Controller start:
    val names = listOf("Mike", "Dennis", "John")
    for (iName in names) {
        val iEmail = "${iName.toLowerCase()}@appifyhub.com"
        service.createSubscriber(NewsSubscriber(email = iEmail, name = iName))
    }
```

2. Adding the data to DB

```kotlin
    // Service:
    fun createSubscriber(subscriber: NewsSubscriber, sendEmail: Boolean = true): NewsSubscriber? {
        val toReturn = safe { subscriberRepo.save(subscriber) }
        println("Data saved: $toReturn")
        toReturn?.let {
            val from = Contact("news@appifyhub.com", "News from AppifyHub")
            val to = listOf(Contact(it.email, it.name))
            val success = Utils.sendEmail(from, to, "News!", "Verify your email for news.. somehow.")
            println("Success sending email: $success")
        }
        return toReturn
    }
```

3. Utils actually sends the email

```kotlin
    // Utils:
    private const val MAILGUN_DOMAIN = "mailgun.appifyhub.com"
    private const val MAILGUN_API_KEY = "the_key"
    private val mailgun: Mailgun = Mailgun.Builder(MAILGUN_DOMAIN, MAILGUN_API_KEY).build()
    fun sendEmail(from: Contact, to: List<Contact>, title: String, text: String = "", html: String = ""): Boolean {
        val builder = SendMessageRequest.Builder(from)
        builder.to(to)
        builder.text(text)
        builder.html(html)
        builder.subject(title)
        val response: SendMessageResponse = mailgun.sendMessage(builder.build()).blockingGet()
        println("Mailgun response: ID=${response.id}, Message=${response.message}")
        // MM not a proper check, still testing
        return response.message?.contains("error")?.not() == true
    }
```

And it crashes on `blockingGet()`. I checked everything, the `Contact` class that I create renders properly `toString()` into `Name <email@domain.com>` format, no $ or other special chars.

**Comment by Jawnnypoo** [comment]
Looks like there is some weird json being returned. Can you add an OkHttp logging interceptor to see what the request and response sent are?

**Comment by milosmns** [comment]
Oh you think the weird JSON is a response? I thought it might be the
request.
Ok, will do. Not now, but will do tomorrow. Thanks!

**Comment by milosmns** [comment]
Added the logger, today it's a different issue, SSL-related:

```
 ...

2018-02-11 14:23:57.108  INFO 1832 --- [           main] okhttp3.OkHttpClient                     : --> POST https://api.mailgun.net/v3/mailgun.appifyhub.com/messages
2018-02-11 14:23:57.109  INFO 1832 --- [           main] okhttp3.OkHttpClient                     : Content-Type: multipart/form-data; boundary=b05a16eb-0812-48d9-9a57-aea08658f55b
2018-02-11 14:23:57.110  INFO 1832 --- [           main] okhttp3.OkHttpClient                     : Content-Length: 693
2018-02-11 14:23:57.110  INFO 1832 --- [           main] okhttp3.OkHttpClient                     : Authorization: Basic my_key
2018-02-11 14:23:57.110  INFO 1832 --- [           main] okhttp3.OkHttpClient                     : 
2018-02-11 14:23:57.111  INFO 1832 --- [           main] okhttp3.OkHttpClient                     : --b05a16eb-0812-48d9-9a57-aea08658f55b
Content-Disposition: form-data; name="from"
Content-Length: 40

News from AppifyHub <news@appifyhub.com>
--b05a16eb-0812-48d9-9a57-aea08658f55b
Content-Disposition: form-data; name="subject"
Content-Length: 5

News!
--b05a16eb-0812-48d9-9a57-aea08658f55b
Content-Disposition: form-data; name="text"
Content-Length: 37

Verify your email for news.. somehow.
--b05a16eb-0812-48d9-9a57-aea08658f55b
Content-Disposition: form-data; name="html"
Content-Length: 0


--b05a16eb-0812-48d9-9a57-aea08658f55b
Content-Disposition: form-data; name="to"
Content-Length: 25

Mike <mike@appifyhub.com>
--b05a16eb-0812-48d9-9a57-aea08658f55b--

2018-02-11 14:23:57.111  INFO 1832 --- [           main] okhttp3.OkHttpClient                     : --> END POST (693-byte body)
2018-02-11 14:23:57.660  INFO 1832 --- [           main] okhttp3.OkHttpClient                     : <-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

...
```

**Comment by milosmns** [comment]
And the stack trace:

```

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'newsSubscriberController': Invocation of init method failed; nested exception is java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:137) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:409) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1620) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at com.appifyhub.service.ApplicationKt.main(Application.kt:14) [classes/:na]
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:91) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.Single.blockingGet(Single.java:2154) ~[rxjava-2.1.3.jar:2.1.3]
	at com.appifyhub.service.utils.Utils.sendEmail(Utils.kt:111) ~[classes/:na]
	at com.appifyhub.service.utils.Utils.sendEmail$default(Utils.kt:105) ~[classes/:na]
	at com.appifyhub.service.service.NewsSubscriberService.createSubscriber(NewsSubscriberService.kt:40) ~[classes/:na]
	at com.appifyhub.service.service.NewsSubscriberService.createSubscriber$default(NewsSubscriberService.kt:29) ~[classes/:na]
	at com.appifyhub.service.controller.NewsSubscriberController.initFakeData(NewsSubscriberController.kt:36) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 18 common frames omitted
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192) ~[na:1.8.0_25]
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1917) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:301) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:295) ~[na:1.8.0_25]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1471) ~[na:1.8.0_25]
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:936) ~[na:1.8.0_25]
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:871) ~[na:1.8.0_25]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1043) ~[na:1.8.0_25]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343) ~[na:1.8.0_25]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371) ~[na:1.8.0_25]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355) ~[na:1.8.0_25]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.9.1.jar:na]
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212) ~[logging-interceptor-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.9.1.jar:na]
	at com.commit451.mailgun.Mailgun$1.intercept(Mailgun.kt:34) ~[mailgun-1.0.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[okhttp-3.9.1.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[okhttp-3.9.1.jar:na]
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) ~[okhttp-3.9.1.jar:na]
	at okhttp3.RealCall.execute(RealCall.java:77) ~[okhttp-3.9.1.jar:na]
	at com.commit451.ehhttp.CallObservable.subscribeActual(CallObservable.kt:20) ~[ehhttp-1.0.0.jar:na]
	at io.reactivex.Observable.subscribe(Observable.java:10903) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.Single.subscribe(Single.java:2700) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.Single.subscribe(Single.java:2700) ~[rxjava-2.1.3.jar:2.1.3]
	at io.reactivex.Single.blockingGet(Single.java:2153) ~[rxjava-2.1.3.jar:2.1.3]
	... 30 common frames omitted
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387) ~[na:1.8.0_25]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292) ~[na:1.8.0_25]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[na:1.8.0_25]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[na:1.8.0_25]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229) ~[na:1.8.0_25]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124) ~[na:1.8.0_25]
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1453) ~[na:1.8.0_25]
	... 69 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145) ~[na:1.8.0_25]
	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131) ~[na:1.8.0_25]
	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280) ~[na:1.8.0_25]
	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382) ~[na:1.8.0_25]
	... 75 common frames omitted
```

The data sent looks ok though.

**Comment by milosmns** [comment]
Everything is fine now, ignore this :) I needed to add a custom X509TrustManager that allows their new cert (not allowed by default). You might want to include it in the lib directly.

**Comment by Jawnnypoo** [comment]
Heya, presently we allow you to provide your own OkHttp client, which allows you to set the trust manager. Is that not enough?

**Comment by milosmns** [comment]
Yes yes, I did that in the end. But I wasn't aware that I needed one in the
first place. It's all fine now :)
The JSON issue was due to the bad URL I was targeting, Mailgun sent a
non-JSON response back, but that's also corrected now.

Thanks for checking this out.

**Comment by Jawnnypoo** [comment]
Ohhh, I see. No worries, glad it is resolved!
